config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :profesionnels do 
    resources :bookings
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :profesionnel
end

app/models/profesionnel.rb
class Profesionnel < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
    @profesionnel = Profesionnel.find(params[:profesionnel_id])
  end

  def show
    @profesionnel = Profesionnel.find(params[:profesionnel_id])
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @profesionnel = Profesionnel.find(params[:profesionnel_id])
  end

  def create
    @booking = Booking.new(book_params)
    @profesionnel = Profesionnel.find(params[:profesionnel_id])
    @booking.profesionnel = @profesionnel
    @booking.user = current_user
    if @booking.save
      redirect_to profesionnel_bookings_path(@profesionnel, @booking)
    else
      render 'new'
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @profesionnel = Profesionnel.find(params[:profesionnel_id])
  end

  def update
    @booking = Booking.find(params[:id])
    @profesionnel = Profesionnel.find(params[:profesionnel_id])
    @booking.update(book_params)
    redirect_to profesionnel_booking_path(@booking, @profesionnel)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @profesionnel = Profesionnel.find(params[:profesionnel_id])
    @booking.destroy
    redirect_to profesionnel_booking_path(@booking, @profesionnel)
  end

  private
  
  def book_params
    params.require(:booking).permit(:date_resa, :total_resa)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/profesionnels_controller.rb
class ProfesionnelsController < ApplicationController
  def index
    @profesionnels = Profesionnel.all
  end

  def show
    @profesionnel = Profesionnel.find(params[:id])
  end

  def new
    @profesionnel = Profesionnel.new
  end

  def create
    @profesionnel = Profesionnel.new(pro_params)
    if @profesionnel.save
      redirect_to profesionnels_path
    else
      render 'new'
    end
  end

  def edit
    @profesionnel = Profesionnel.find(params[:id])
  end

  def update
    @profesionnel = Profesionnel.find(params[:id])
    @profesionnel = Profesionnel.update(pro_params)
    redirect_to profesionnel_path(profesionnel)
  end

  def destroy
    @profesionnel = Profesionnel.find(params[:id])
    @profesionnel.destroy
    redirect_to profesionnels_path
  end

  private

  def pro_params
    params.require(:profesionnel).permit(:name, :adress, :category, :tarif, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1>MES BOOKINGS</h1>
<% @bookings.each do |booking| %>
<p><%= booking.date_resa %> <%= booking.total_resa %>$ <%= booking.profesionnel.name %></p>
<% end %>
<%= link_to "retour a l'index", profesionnels_path, class: "btn btn-primary"  %>

app/views/bookings/new.html.erb
<<p>Créer une reservation</p>

<%= simple_form_for([@profesionnel,@booking]) do |b| %>

  <%= b.input :date_resa %>
  <%= b.input :total_resa %>
  <%= b.submit class: "btn btn-primary" %>
<% end %>

<%= link_to "retour a l'index", profesionnels_path, class: "btn btn-primary"  %>
<%# <%= link_to "voir mes bookings",   %> 

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindCoach</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Trouve ton <strong> coach</strong> partout <strong>quand tu veu </strong>!</h1>
    <p>Sport is life</p>
    <%= link_to "Voir la liste des coachs", profesionnels_path, class: "btn btn-flat"  %>
  </div>
</div>

app/views/profesionnels/create.html.erb
<h1>Profesionnels#create</h1>
<p>Find me in app/views/profesionnels/create.html.erb</p>

app/views/profesionnels/destroy.html.erb
<h1>Profesionnels#destroy</h1>
<p>Find me in app/views/profesionnels/destroy.html.erb</p>

app/views/profesionnels/edit.html.erb
<h1>Modifier un profesionnel</h1>
<%= simple_form_for(@profesionnel) do |c| %>
  <%= c.label :name %>
  <%= c.text_field :name %>
  <%= c.label :adress %>
  <%= c.text_field :adress %>
  <%= c.label :category %>
  <%= c.text_field :category %>
  <%= c.label :tarif %>
  <%= c.text_field :tarif %>
  <%= c.submit class:"btn btn-primary" %>
<% end %>
<br>
<%= link_to "retour a l'index", profesionnels_path, class: "btn btn-primary"  %>

app/views/profesionnels/index.html.erb
<h1>Liste des coachs dispo</h1>
<% @profesionnels.each do |profesionnel|   %>
<div class="container-flexed">
  <div class="card-product">
    <% if profesionnel.photo.attached? %>
      <%= cl_image_tag profesionnel.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
    <% end %>
  </div>
    <div class="info"> <p>nom: <%= profesionnel.name %><br> adresse: <%= profesionnel.adress %><br> category: <%= profesionnel.category %><br> prix: <%= profesionnel.tarif %>$</p></div>
      <div class="btns">
        <%= link_to "Book this coach", new_profesionnel_booking_path(profesionnel, @booking), class:"btn btn-primary" %>
        <%= link_to "edit", edit_profesionnel_path(profesionnel), class:"btn btn-primary" %>
        <%= link_to "",
            profesionnel_path(profesionnel),
            method: :delete,
            class: "fa fa-trash",
            data: { confirm: "Are you sure?" } %>
        </div>
  </div>
<%= link_to "Voir mes bookings",  profesionnel_bookings_path(profesionnel, @booking), class: "btn btn-flat" %> 
<% end %>
<br>
<br>
<%= link_to "Create a profesionnel", new_profesionnel_path, class:"btn btn-primary" %>
<%= link_to "retour a l'index", root_path, class: "btn btn-primary"  %>

app/views/profesionnels/new.html.erb
<h1>Creer un profesionnel</h1>
<%= simple_form_for(@profesionnel) do |c| %>
  <%= c.label :name %>
  <%= c.text_field :name %>
  <%= c.label :adress %>
  <%= c.text_field :adress %>
  <%= c.label :category %>
  <%= c.text_field :category %>
  <%= c.label :tarif %>
  <%= c.text_field :tarif %>
  <%= c.input :photo, as: :file %>
  <%= c.submit class:"btn btn-primary" %>
<% end %>
<br>
<%= link_to "retour a l'index", profesionnels_path, class: "btn btn-primary"  %>

app/views/profesionnels/show.html.erb
<h1>Profesionnels#show</h1>
<p>Find me in app/views/profesionnels/show.html.erb</p>

app/views/profesionnels/update.html.erb
<h1>Profesionnels#update</h1>
<p>Find me in app/views/profesionnels/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>